version: '3.3'
services:
  mysqldev:
    container_name: mysqlDev
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./docker/mysql_init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      - ./scripts/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  activityrankmanagerdev:
    container_name: activityRankManagerDev
    restart: always
    build: .
    depends_on:
      - mysqldev
    links:
      - mysqldev
    volumes:
      - ./src:/usr/src/app
      #- /usr/src/app/node_modules
    command: npm run development
    ports:
      - "3005:3005"
